name: 'OpenFaaS CLI Action'
description: 'CLI commands to your OpenFaaS Gateway'
author: 'Denys Vasyliev'
inputs:
  command:
    description: 'OpenFaaS Command'
    required: true
    default: 'deploy'
  path:
    description: "Path to stack YAML file"
    default: "stack.yml"
    required: true
  options_name:
    description: 'commands options'
    required: false
  options_value:
    description: 'commands options'
    required: false

runs:
  using: 'docker'
  image: 'docker://openfaas/faas-cli:0.12.4'
  args:
    - 'faas-cli'
    - '${{ inputs.command }}'
    - '-f=${{ inputs.path }}'
    - '${{ inputs.options_name }}' '${{ inputs.options_value }}'
